---
- name: Create and start one ec2 instance
  hosts: localhost
  tasks:
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "public-compute-instance"
        key_name: "vockey"
        instance_type: t4g.nano
        security_group: default
        network_interfaces:
          - assign_public_ip: true
        image_id: ami-0325498274077fac5
        tags:
          Environment: Testing