---
- name: Remove conflicted package
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
  tags:
    - clean

- name: Install first dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
  tags:
    - dep

- name: Install docker repo
  block:
    - name: Somerepo | no apt key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/myrepo.asc

    - name: Somerepo | apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch={{dpkg_arch}} signed-by=/etc/apt/keyrings/myrepo.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

- name: Install docker engine package
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin

